In [1]:
import pandas as pd
import xlwings as xw

In [2]:
data = pd.read_csv('AAPL.csv', index_col='Date')
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-10-25,217.710007,221.380005,216.750000,219.800003,216.441330,29855800
2018-10-26,215.899994,220.190002,212.669998,216.300003,212.994797,47258400
2018-10-29,219.190002,219.690002,206.089996,212.240005,208.996857,45935500
2018-10-30,211.149994,215.179993,209.270004,213.300003,210.040649,36660000
2018-10-31,216.880005,220.449997,216.619995,218.860001,215.515686,38358900
2018-11-01,219.050003,222.360001,216.809998,222.220001,218.824341,58323200
2018-11-02,209.550003,213.649994,205.429993,207.479996,204.309570,91328700
2018-11-05,204.300003,204.389999,198.169998,201.589996,198.509583,66163700
2018-11-06,201.919998,204.720001,201.690002,203.770004,200.656265,31882900
2018-11-07,205.970001,210.059998,204.130005,209.949997,206.741821,33424400
2018-11-08,209.979996,210.119995,206.750000,208.490005,206.020493,25362600
2018-11-09,205.550003,206.009995,202.250000,204.470001,202.048096,34365800
2018-11-12,199.000000,199.850006,193.789993,194.169998,191.870087,51135500
2018-11-13,191.630005,197.179993,191.449997,192.229996,189.953079,46882900
2018-11-14,193.899994,194.479996,185.929993,186.800003,184.587402,60801000
2018-11-15,188.389999,191.970001,186.899994,191.410004,189.142792,46478800
2018-11-16,190.500000,194.970001,189.460007,193.529999,191.237686,36928300
2018-11-19,190.000000,190.699997,184.990005,185.860001,183.658539,41925300
2018-11-20,178.369995,181.470001,175.509995,176.979996,174.883713,67825200
2018-11-21,179.729996,180.270004,176.550003,176.779999,174.686081,31124200
2018-11-23,174.940002,176.600006,172.100006,172.289993,170.249252,23624000
2018-11-26,174.240005,174.949997,170.259995,174.619995,172.551666,44998500
2018-11-27,171.509995,174.770004,170.880005,174.240005,172.176163,41387400
2018-11-28,176.729996,181.289993,174.929993,180.940002,178.796799,46062500
2018-11-29,182.660004,182.800003,177.699997,179.550003,177.423264,41770000
2018-11-30,180.289993,180.330002,177.029999,178.580002,176.464767,39531500
2018-12-03,184.460007,184.940002,181.210007,184.820007,182.630859,40802500
2018-12-04,180.949997,182.389999,176.270004,176.690002,174.597153,41344300
2018-12-06,171.759995,174.779999,170.419998,174.720001,172.650482,43098400
2018-12-07,173.490005,174.490005,168.300003,168.490005,166.494278,42281600
...,...,...,...,...,...,...
2019-09-16,217.729996,220.130005,217.559998,219.899994,219.899994,21158100
2019-09-17,219.960007,220.820007,219.119995,220.699997,220.699997,18318700
2019-09-18,221.059998,222.850006,219.440002,222.770004,222.770004,25340000
2019-09-19,222.009995,223.759995,220.369995,220.960007,220.960007,22060600
2019-09-20,221.380005,222.559998,217.470001,217.729996,217.729996,55413100
2019-09-23,218.949997,219.839996,217.649994,218.720001,218.720001,19165500
2019-09-24,221.029999,222.490005,217.190002,217.679993,217.679993,31190800
2019-09-25,218.550003,221.500000,217.139999,221.029999,221.029999,21903400
2019-09-26,220.000000,220.940002,218.830002,219.889999,219.889999,18833500
2019-09-27,220.539993,220.960007,217.279999,218.820007,218.820007,25352000
2019-09-30,220.899994,224.580002,220.789993,223.970001,223.970001,25977400
2019-10-01,225.070007,228.220001,224.199997,224.589996,224.589996,34805800
2019-10-02,223.059998,223.580002,217.929993,218.960007,218.960007,34612300
2019-10-03,218.429993,220.960007,215.130005,220.820007,220.820007,28606500
2019-10-04,225.639999,227.490005,223.889999,227.009995,227.009995,34619700
2019-10-07,226.270004,229.929993,225.839996,227.059998,227.059998,30576500
2019-10-08,225.820007,228.059998,224.330002,224.399994,224.399994,27955000
2019-10-09,227.029999,227.789993,225.639999,227.029999,227.029999,18692600
2019-10-10,227.929993,230.440002,227.300003,230.089996,230.089996,28253400
2019-10-11,232.949997,237.639999,232.309998,236.210007,236.210007,41698900
2019-10-14,234.899994,238.130005,234.669998,235.869995,235.869995,24106900
2019-10-15,236.389999,237.649994,234.880005,235.320007,235.320007,21840000
2019-10-16,233.369995,235.240005,233.199997,234.369995,234.369995,18475800
2019-10-17,235.089996,236.149994,233.520004,235.279999,235.279999,16896300
2019-10-18,234.589996,237.580002,234.289993,236.410004,236.410004,24358400
2019-10-21,237.520004,240.990005,237.320007,240.509995,240.509995,21811800
2019-10-22,241.160004,242.199997,239.619995,239.960007,239.960007,20573400
2019-10-23,242.100006,243.240005,241.220001,243.179993,243.179993,18957200
2019-10-24,244.509995,244.800003,241.809998,243.580002,243.580002,17318800
2019-10-25,243.160004,246.720001,242.889999,246.580002,246.580002,15827692

In [ ]:
# View the data in Excel
xw.view(data)

In [ ]:
# Create a new Excel workbook
wb = xw.Book()

In [ ]:
# Write a DataFrame
wb.sheets[0]['A1'].value = data

In [ ]:
# Read a DataFrame
wb.sheets[0]['A1'].options(pd.DataFrame, expand='table').value